-- Car Decor Manager V2.15
-- Configurable standard service prices.

CREATE TABLE IF NOT EXISTS public.service_prices (
  id bigint generated by default as identity primary key,
  service_name text not null unique,
  selling_price numeric(12,2) not null default 0,
  cost_price numeric(12,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

INSERT INTO public.service_prices (service_name, selling_price, cost_price)
VALUES
  ('Car Washing', 600, 0),
  ('Alignment & Balancing', 600, 0)
ON CONFLICT (service_name) DO NOTHING;

ALTER TABLE public.service_prices ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON TABLE public.service_prices TO anon;
GRANT SELECT, UPDATE ON TABLE public.service_prices TO authenticated;

DROP POLICY IF EXISTS "Anyone can view active service prices" ON public.service_prices;
CREATE POLICY "Anyone can view active service prices"
ON public.service_prices
FOR SELECT
TO anon, authenticated
USING (active = true);

DROP POLICY IF EXISTS "Authenticated admin can update service prices" ON public.service_prices;
CREATE POLICY "Authenticated admin can update service prices"
ON public.service_prices
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);
