-- Car Décor Business Manager - Supabase schema
-- Run this in Supabase SQL Editor after creating a project.

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  selling_price numeric(12,2) not null check (selling_price >= 0),
  cost_price numeric(12,2) not null check (cost_price >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists sales (
  id bigint generated by default as identity primary key,
  sale_date date not null default current_date,
  sale_time timestamptz not null default now(),
  car_last4 varchar(4) not null check (car_last4 ~ '^[0-9]{4}$'),
  category text not null,
  product_id bigint references products(id),
  item_name text not null,
  selling_price numeric(12,2) not null check (selling_price >= 0),
  cost_price numeric(12,2) not null check (cost_price >= 0),
  created_at timestamptz not null default now()
);

create table if not exists expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null default current_date,
  expense_type text not null,
  description text,
  amount numeric(12,2) not null check (amount >= 0),
  created_at timestamptz not null default now()
);

-- Standard services can be seeded as products if desired,
-- but the app treats these as fixed-price services:
-- Car Washing = ₹600
-- Alignment & Balancing = ₹600

alter table products enable row level security;
alter table sales enable row level security;
alter table expenses enable row level security;

-- For the first private prototype, do NOT expose these tables publicly.
-- Add authenticated-user policies after Supabase Auth is configured.
